name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 8
          java-package: jdk
          cache: maven

      - name: Build and tag Docker image
        run: docker build -t your-docker-repo:latest .

      - name: Push Docker image
        run: docker push your-docker-repo:latest

      - name: Deploy to EC2 instance
        run: |
          ssh -o "StrictHostKeyChecking no" -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@44.195.62.118 "docker pull your-docker-repo:latest && docker run -d -p 80:80 your-docker-repo:latest"
