name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up Docker
      #   uses: docker/setup-buildx-action@v1

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and tag Docker image
      #   run: docker build -t lucassusinedu/sarcng-repo:latest .

      # - name: Push Docker image
      #   run: docker push lucassusinedu/sarcng-repo:latest

      # - name: Install SSH key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     name: id_rsa
      #     known_hosts: ec2-44-195-62-118.compute-1.amazonaws.com

      - name: Deploy to EC2 instance
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > key.pem
          chmod 400 key.pem 
          ssh -i key.pem  -o "MIIEowIBAAKCAQEAiet2nYTixluNaMq79BTskdKuZFD0w5B6ieOaVh7ok41nTCuUoCw0xa8l25Y7cS/7t+xFEHVbJHh7y+vmgRUME9RZkhbLe5VqkwP0oWprCcdP9yReZEoei6YodeZVxgwWCdempmzG/3ynbuXucETtyK+uBgsp63X8P5+ytvwiNXF6AogwAsLA/EBQqkltA7HB2aYe8sD9AkzkClypuM/3Cd8Pii7Ea360ZoFG4y1qjvqKHl3JOou9mmiOMbham96X+FdhFBkMPdWn6EkRWTJW7Y1BISjNfBpFFSN681ebVzN1EbxtlhJrDqzMQn/136uZdutUlpq838WcnEgdTS5v4QIDAQABAoIBAH7/783E2/3DuEdSyBhOXDk7Q5LkaT7b/7qRd0DuXUPh5cjiKI4FpuKSEc5OXJYxlR0b18z8A91lhLmWlD8w3lo0I/a+PsmiIO0Xq2An2kC65Auz1aeMCOyXKJLIcxtXbcPKbI67g9MnOhaIbDO9hShTfW/bP9KuZoU/zRVqvyVt3eXc/XHvfkEKBx0FJvhq4P2DVFm7AIH1fQW30S2lxMZzMqbrE9wYcVs3lcNlSAjeue+BEkB0Iqd+QCb0XpaM33YHlH7ZgCv8Zsr1eHARIsMX18himUl618LQxoDDqf2evq8bEULMnoupbjgvFIdS/2KrNiC/hl95PleHZeizvUECgYEA9tNhvu2mxiPD3/fYppTSjccVXq9N3KInnQgJW9PsTZo5rjC4RnTWCnUV2KPGcZV8Pw/s6OWnR775wKFYPcFCu4M/R/BVvSbH1LC3V1s6SQ9MO94i9z+3F7N6DuH7wXBI2ZR/IOiUKfSzH+qxzHOTK8FeQcd6v1VDEUBUCO7pEaUCgYEAjwvPXRTZzYnE6TWnpoav/eQn6cwZCFPVzWr/vYWiTo2hCB8VsX/lkt4fbPq4A+1MZQZ8rcJ/SFDiGo+PClRGAp+nki5PB5i0ut7OpSYGOkXrQDVjHweDh8xbG6prka4AdhD1jKM27cIlJBJgEFsGr6M2Xk5g63oRz7PwuuTWI0CgYEAn8vYQ2DekPbEsDJoa+h7rFhQaH18HjRJCywRywaXvOH1J+XY15x6mkiVPS1Co3SQ/M7VpS5RL2zfiquqUkjVaEqfZHafO5do1jUWbZLdWEF0LGozHvl8EvcaNZpugByuvVabO3X3vnXypd4u/9tvU2ucF2ALAuYzRm7sOOBbuhUCgYBXliOiGuJBt9mZ8gB1NoMMMmc+AHpTXwHKhXmR0gFPl+jB0Ea4KFepVdhoIhwKS4I7WX1951mILf5DxSMQcAluEdPI7hH11MrUoRhmhqHJjIY/CnFmznL682XVysOSr7gYks7aGJmm7quSS8a1gVlwBry3bEKLHjDbbtpHv3a5AQKBgGsN8AylobDZGxmiG+NG8KH4NSTMJb3dEBDJ+duP5ZF7kUsbwsgWybPdPEAt7WmnKKaw0zdX1QyJ570WQ5sljKDRzztHm1l/UaQpzrgjVULGRRcQlkCSHoh+DFdVUFRIsEAIsLRBSfdHuUQ9HGYVlydRPuuacLjPaN3T/9PGywGy" ubuntu@ec2-44-195-62-118.compute-1.amazonaws.com
