name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 8
          java-package: jdk
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
