name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and tag Docker image
      #   run: docker build -t lucassusinedu/sarcng-repo:latest .

      # - name: Push Docker image
      #   run: docker push lucassusinedu/sarcng-repo:latest

      - name: Deploy to EC2 instance
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o "StrictHostKeyChecking no" -i private_key ubuntu@ec2-44-195-62-118.compute-1.amazonaws.com "docker pull lucassusinedu/sarcng-repo:latest && docker run -d -p 80:80 lucassusinedu/sarcng-repo:latest"
