name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 8
          java-package: jdk
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Exec Jar File
        run: sudo kill -9 `sudo lsof -t -i:8080` & sudo java -jar /home/ubuntu/actions-runner/_work/sarcng/sarcng/target/sarcng-0.0.1-SNAPSHOT.jar
