name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Test Project
        uses: gradle/wrapper-validation-action@v1
        with:
          java-version: 11
          distribution: "adopt"

      - name: Build Project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      # - name: Set up Docker
      #   uses: docker/setup-buildx-action@v1

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and tag Docker image
      #   run: docker build -t lucassusinedu/sarcng-repo:latest .

      # - name: Push Docker image
      #   run: docker push lucassusinedu/sarcng-repo:latest

      # - name: Docker pull and run image
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ec2-44-195-62-118.compute-1.amazonaws.com
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     envs: GITHUB_SHA
      #     script: |
      #       docker login
      #       docker pull ${{ secrets.DOCKER_USERNAME }}/sarcng-repo:latest
      #       docker stop

      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     REMOTE_HOST: ec2-44-195-62-118.compute-1.amazonaws.com
      #     REMOTE_USER: ubuntu
      #     TARGET: /home/ubuntu/sarcng-repo
